### ISSUE TITLE
Update core growth funnel, roles, process, tracking

### ISSUE THREAD

**Issue by dazuck** [3box/ops#472]
- [ ] what's the goal and strategy for different segments 
- [ ] who is involved and how
- [ ] what is the tool (notion or other crm) 
- [ ] how do we get good feedback loops & metrics
