### ISSUE TITLE
Ensure EthDenver learnings make it into roadmap 

### ISSUE THREAD

**Issue by dazuck** [3box/ops#678]
Make sure we take advantage of our learnings 

- [ ] Execute any easy to do docs, callouts,etc. 

- [ ] Put bigger things into backlog for discussion at roadmap/product meetings 

- [ ] Anything else needed to share learnings across the team
